### ISSUE TITLE
ble module not visible

### ISSUE THREAD

**Issue by gdanas87** [zosko/iNavTelemetry#1]
iPhone 8 Plus ios 14.5.1, latest inav telemetry app from Apple store: At first I thought that the iPhone cant "see" the Bluetooth module inside my t16 due to the usual Apple mfi bull, but that is not the case. The inav telemetry App never sees my t16 ble bt module, but it turns out the phone can see it since I tested with speedy Bee app and to my surprise it sees the t16 (picture attached)
![118340088-66510280-b523-11eb-9fd1-e87cdcdc720a](https://user-images.githubusercontent.com/60666086/118356195-bc9e5f80-b57c-11eb-86ed-a099f84fc81b.png)

Is there any chance the app can be fixed to see all ble devices?

**Comment by zosko** [comment]
> Is there any chance the app can be fixed to see all ble devices?
Can you tell me what Transmitter you have or bluetooth module you using?

**Comment by gdanas87** [comment]
> > Is there any chance the app can be fixed to see all ble devices?
> > Can you tell me what Transmitter you have or bluetooth module you using?

Thank you for the quick reply
I am using the jumper t16 pro and have soldered the frsky ble module https://www.horusrc.com/en/frsky-transmitter-horus-x12s-bluetooth-module.html into the dedicated pads for bt on the jumper t16 mainboard just like this picture . I tried with telemetry app for android from crazydude developer and on android it works just fine for telemetry viewing
![67623104-b5402580-f821-11e9-81a2-942b357effbc](https://user-images.githubusercontent.com/60666086/118374518-3ce8b300-b5c5-11eb-9f88-ddd53c52b821.jpg) sadly i do not own an android device and only used my wife's for testing so I was hoping my iphone with your sweet sweet app can play nice with my setup for telemetry viewing

**Comment by zosko** [comment]
Ohh i see now, on AppStore there is initial version only. I github is latest version and working with that module ( i have same ). But seems you dont have xCode to install on your phone. For AppStore new version i will try to update soon as possible.

**Comment by gdanas87** [comment]
> Ohh i see now, on AppStore there is initial version only. I github is latest version and working with that module ( i have same ). But seems you dont have xCode to install on your phone. For AppStore new version i will try to update soon as possible.

Thats amazing im so glad. Can I use xcode to install the App on my phone too? I will research into it... Sad thing is I was on ios 13 yesterday and decided to upgrade to 14.5 instead of jailbreaking, hoping that would fix my problem.

**Comment by zosko** [comment]
@gdanas87  try new version from appstore

**Comment by gdanas87** [comment]
> @gdanas87 try new version from appstore

Wow it does see it and connects 
![0A452213-563C-49F0-BAC1-11174827AD86](https://user-images.githubusercontent.com/60666086/118390299-f764ce00-b636-11eb-9fe4-ba56525754c3.png)
 I get data, thats amazing!!!! 

 However after 1 minute it disconnects, same happened with an old Lenovo tablet I tried, must be some incompatibility of the bt hardware of the iPhone 8 plus.

**Comment by gdanas87** [comment]
tried restarting my phone, disconnect issues have gone away so far! :D thats a sweet looking app :D

**Comment by gdanas87** [comment]
> tried restarting my phone, disconnect issues have gone away so far! :D thats a sweet looking app :D

sadly i get random disconnects again. I dont think its the app's fault though... probably some type of incompatibility of the iphone's bt module. I get same disconnects on lenovo tablet android with crazydude app, but not with my wife's samsung s10. So i am guessing some hardware incompatibility on the phone side here. Great work though!

**Comment by zosko** [comment]
I will close this issue, please create new issue for that disconnect, i will debug on mine side and see why is disconnecting. Maybe Frsky bluetooth module disconnect or something else happen.

**Comment by gdanas87** [comment]
thank you, will do!
