### ISSUE TITLE
Direction to airplane location

### ISSUE THREAD

**Issue by kvng1** [zosko/iNavTelemetry#11]
Hello,
Is it possible to have a small arrow on the screen pointing to the aircraft location by using phone's compass? It's super helpful in aiming antenna and in finding lost model.

**Comment by wx4cb** [comment]
why not just punch in the gps coordinates and go from there? not to mention that phone compasses are notoriously inaccurate and drift like hell

**Comment by kvng1** [comment]
It's mainly for pointing the directional antenna to the aircraft while flying. With analog vtx, I can easily turn myself to the aircraft base on image quality, not anymore with dji hd.

**Comment by wx4cb** [comment]
the issue with that is that the script has no idea where it is and which way it's pointing (due to no compass), so has no way of calculating that. 

if i was you i'd get a tracker that runs off the radio link telemetry that you can get either via BT, wifi (crossfire) or over the serial port. besides.... if you're taking your bearing from a screen on the transmitter, what if you now turn around.... that bearing is going to be way off.

**Comment by kvng1** [comment]
Could add a little compass module on spare uart https://abra-electronics.com/wireless/gps/modules/sens-gy-26-digital-compass-module.html Location is from aircraft gps when arming.
Yes, I can do similar thing with external antenna tracker, just don't want to carry more thing to the field.

**Comment by wx4cb** [comment]
no point putting a compass on the radio unless the firmware supports it, which i doubt... the issue with the location is the script does not store the location for the home point. AFAIK.

my tracker is on a small mic stand so is fine, only thing that's a pita is carrying the extra batteries, but seeing as i have to take my car anyway no biggie

**Comment by wx4cb** [comment]
and i digress... but this is where knowing where you're flying comes into it :D you should always know the terrain and where you are heh but that's just me

**Comment by zosko** [comment]
Hey, from pilot i can get GPS location and Compass. From Drone / Airplane we have GPS coordinate. So with trigonometry this can be archived to point to your Drone / Airplane . I can prepare that.

**Comment by zosko** [comment]
@kvng1  i just update code to support direction to model i made simulation and looks good, i did not tested on real model, i will test some nice day.

![](https://user-images.githubusercontent.com/3172271/182951153-94142f77-d61f-4a2a-b13b-fc0469937754.mp4)
