### ISSUE TITLE
Display altitude above ground level 

### ISSUE THREAD

**Issue by mattcave** [zosko/iNavTelemetry#6]
The app currently displays altitude above sea level, rather than above ground level (or above launch/arm point). I think the latter would be more useful for most people. Could be a configurable option?

**Comment by zosko** [comment]
I have old idea, when you tap on that value it will flip and display second value, example.. if you tap on Altitude it will display `above sea` and when you tap again will display `above ground` .

**Comment by mattcave** [comment]
That would work well. If you do that, it would be good to add a visual cue that the value can be interacted with, to make it more intuitive.
